### ISSUE TITLE
dandi download doesn't work, typing.py error, Windows 10, Python 3.7.2

### ISSUE THREAD

**Issue by vickerse1** [dandi/dandi-cli#1396]
I used pip install dandi on windows 10, then received the following error when I typed in "dandi download https://dandiarchive.org/dandiset/XXXXXX/draft" (anaconda prompt, Python 3.72):

```
-----------------
(base) D:\meso_methods_draft_Feb1623_GDRIVE\eLife_submission_Nov0223\revision_Jan08_2024\DANDISET>dandi download https://dandiarchive.org/dandiset/000879/draft
2024-01-29 15:38:52,785 [ WARNING] A newer version (0.59.0) of dandi/dandi-cli is available. You are using 0.55.0
2024-01-29 15:38:53,150 [    INFO] Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2024-01-29 15:38:54,411 [    INFO] Logs saved in C:\Users\McCormick Lab\AppData\Local\dandi\dandi-cli\Logs\20240129233852Z-116396.log
Error: cannot import name 'Literal' from 'typing' (c:\programdata\anaconda3\lib\typing.py)
------------------------
```

Then I uninstalled with pip uninstall dandi, and tried conda forge....the installation failed.

Finally, I went back and used the pip install again, and received the same error.

Can you help me?

Thanks,

Evan

**Comment by yarikoptic** [comment]
what do you see when you run `pip install --upgrade dandi===0.59.0` ?

> , and tried conda forge....the installation failed.

it failed how?  please cut/paste your invocation of `conda install -c conda-forge dandi` with output you are getting

**Comment by vickerse1** [comment]
when i run pip install --upgrade dandi===0.59.0 I get:

-------------------
(base) C:\dandi\dandi-cli>pip install --upgrade dandi===0.59.0
WARNING: Ignoring invalid distribution -illow (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -orch (c:\programdata\anaconda3\lib\site-packages)
ERROR: Ignored the following yanked versions: 0.0.2, 0.1, 0.2.0
ERROR: Ignored the following versions that require a different python version: 0.55.1 Requires-Python >=3.8; 0.56.0 Requires-Python >=3.8; 0.56.1 Requires-Python >=3.8; 0.56.2 Requires-Python >=3.8; 0.57.0 Requires-Python >=3.8; 0.58.0 Requires-Python >=3.8; 0.58.1 Requires-Python >=3.8; 0.58.2 Requires-Python >=3.8; 0.59.0 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement dandi===0.59.0 (from versions: 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.5.0, 0.6.0rc1, 0.6.0, 0.6.1, 0.6.2, 0.6.4, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.16.0, 0.17.0, 0.18.0, 0.19.0, 0.20.0, 0.21.0, 0.22.0, 0.23.0, 0.23.1, 0.23.2, 0.24.0, 0.25.0, 0.26.0, 0.26.1, 0.27.0, 0.27.1, 0.27.2, 0.27.3, 0.28.0, 0.29.0, 0.30.0, 0.30.1, 0.30.2, 0.30.3, 0.31.0, 0.32.0, 0.32.1, 0.32.2, 0.33.0, 0.34.0, 0.34.1, 0.35.0, 0.36.0, 0.37.0, 0.38.0, 0.39.0, 0.39.1, 0.39.2, 0.39.3, 0.39.4, 0.39.5, 0.39.6, 0.40.0, 0.40.1, 0.41.0, 0.42.0, 0.43.0, 0.44.0, 0.44.1, 0.45.0, 0.45.1, 0.46.1, 0.46.2, 0.46.3, 0.46.4, 0.46.5, 0.46.6, 0.47.0, 0.48.0, 0.48.1, 0.49.0, 0.49.1, 0.50.0, 0.50.1, 0.51.0, 0.52.0, 0.53.0, 0.54.0, 0.55.0)
ERROR: No matching distribution found for dandi===0.59.0
---------------------

sorry, I lost my conda-forge error.

just now I tried using gitclone, then installed a dandi-cli environment in python 3.9, activated the environment and tried my command again...received same error:

---------------

(dandi-cli) C:\dandi\dandi-cli>dandi download https://dandiarchive.org/dandiset/000879/draft
2024-01-29 15:57:40,327 [ WARNING] A newer version (0.59.0) of dandi/dandi-cli is available. You are using 0.55.0
2024-01-29 15:57:40,691 [    INFO] Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2024-01-29 15:57:41,984 [    INFO] Logs saved in C:\Users\McCormick Lab\AppData\Local\dandi\dandi-cli\Logs\20240129235739Z-139304.log
Error: cannot import name 'Literal' from 'typing' (c:\programdata\anaconda3\lib\typing.py)
-------------------

thanks,

evan

________________________________

**Comment by jwodder** [comment]
`dandi` has required Python 3.8+ ever since v0.55.1; it doesn't work on Python 3.7, and you shouldn't even have been able to install it on that version.

**Comment by jwodder** [comment]
Show the command you used to create & install in the Python 3.9 environment.

**Comment by vickerse1** [comment]
conda create --name dandi-cli python=3.9

...but now when i ran pip install --upgrade dandi===0.59.0 in the environment it worked and i got:

"please provde API key for dandi:"

so key was knowing specific python version to use and to know that 0.59.0 is the best current version of dandi to use

neither of these things was clear in the instructions/documentation

thanks

evan

________________________________

**Comment by yarikoptic** [comment]
that dandiset is embargoed so needs a key to access.  Given that previously your `dandi` command was not working at all, I suspect that API key was never provided before, and hence `dandi` is asking for it now.

Please feel free to recommend specific changes to instructions/documentations which you think could have helped you along this route.
